# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "record", # <ts_match_names>
  "id", # <ts_match_names>
  "name", # <ts_match_names>
  "match_type", # <ts_match_names>
  "record", # <ts_parse_names>
  "id", # <ts_parse_names>
  "name", # <ts_parse_names>
  NULL
))
