# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "namestring", # <ts_match_names>
  "id", # <ts_match_names>
  "key_id", # <ts_match_names>
  "record", # <ts_match_names>
  "name", # <ts_match_names>
  "match_type", # <ts_match_names>
  "record", # <ts_parse_names>
  "id", # <ts_parse_names>
  "name", # <ts_parse_names>
  "reference", # <ts_resolve_names>
  "match_type", # <ts_resolve_names>
  "result_type", # <ts_resolve_names>
  "acceptedNameUsageID", # <ts_resolve_names>
  "taxonID", # <ts_resolve_names>
  "taxonomicStatus", # <ts_resolve_names>
  "scientificName", # <ts_resolve_names>
  "resolved_name", # <ts_resolve_names>
  "resolved_status", # <ts_resolve_names>
  "n", # <ts_resolve_names>
  "matched_name", # <ts_resolve_names>
  "matched_status", # <ts_resolve_names>
  "query", # <ts_classify_result>
  "result_type", # <ts_classify_result>
  "n", # <ts_classify_result>
  NULL
))
